import React from 'react';
export const ENGINE_CATEGORIES = [
 {category:'Care · telemedicine',name:'Sunshine Pocket Therapy',text:'Begin with the Hero. Make room for care as you describe your vision and the life you want to grow into.',cue:'What support would help me care for my mind, body and soul?'},
 {category:'UFO · legal',name:'WealthCounsel',text:'Give your family office a structure. Gather the intentions and questions behind the legal drafting you need.',cue:'What do I want my family office to hold and protect?'},
 {category:'Travel',name:'On my way!',text:'Bring the places, people and journeys in your story into view.',cue:'Where do I want to go, and who is coming with me?'},
 {category:'Home server',name:'Sanctuary Cell',text:'Create a home for your digital world. Start with what you have and what you want your home server to make possible.',cue:'What would I like to bring home into my own digital space?'},
 {category:'Technology · tech and kitchen',name:'The Cookbook',text:'Cookbook your way into a functional family office, with practical recipes for your technology and your kitchen.',cue:'What would I like to learn to make or set up?'},
 {category:'Funding · financial',name:'Soup Club',text:'Explore the business side of funding: insurance leads, commissions and the work needed to support your plans.',cue:'What needs funding, and what business activity could support it?'}
];
export default function EngineJourney(){return <section className="lm-engine" id="engine-care"><p className="lm-kicker">CARE & SUPPORT</p><h2 className="lm-section-title">The support behind your happily ever after.</h2><p>Hero, choose what your wish needs today. These are service categories within the Engine; your Houses organize the products and tools you use.</p><details className="lm-care-disclosure"><summary>Explore the Engine’s care and service offerings</summary><div className="lm-engine-grid">{ENGINE_CATEGORIES.map(x=><details key={x.name}><summary><small>{x.category}</small><h3>{x.name}</h3><span>Explore this part of the Engine +</span></summary><p>{x.text}</p><blockquote>{x.cue}</blockquote><a href="#wish-well">Bring this to the WISH WELL ↑</a></details>)}</div></details><p className="lm-caption">Explore the offerings here. Booking, enrollment and provider connections are not active in this preview.</p></section>}
