import React,{useState,useEffect} from 'react';
import {GATES,GateState,GateRecord,readGates,gateProgress} from '../gates';
import LorraineMadreChat,{StoryDraft} from './LorraineMadreChat';
const EDGES=[[12,9],[9,1],[9,2],[1,2],[1,3],[2,3],[1,11],[2,10],[11,3],[3,10],[11,8],[10,7],[3,8],[3,7],[8,4],[7,4],[8,5],[5,4],[4,13],[5,13],[13,6]];
export function GateTree({state,onSelect}:{state:GateState;onSelect:(h:number)=>void}){return <div className="lm-gate-tree" aria-label="WISH WELL gate map"><svg viewBox="0 0 560 875" aria-hidden="true">{EDGES.map(([a,b])=>{const p=GATES.find(g=>g.house===a)!;const q=GATES.find(g=>g.house===b)!;return <line key={`${a}-${b}`} x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke={a===12||b===6?'#b8b8b8':'#d6d6d2'} strokeWidth="1" strokeDasharray={a===12||b===6?'3 6':undefined}/>;})}</svg>{GATES.map(g=>{const progress=gateProgress(state.records[g.house]);return <button key={g.house} className={`lm-gate-node ${state.selected===g.house?'is-current':''} ${progress===100?'is-reviewed':''}`} style={{left:`${g.x/560*100}%`,top:`${g.y/875*100}%`}} aria-pressed={state.selected===g.house} aria-label={`Gate ${g.house}: ${g.title}, ${progress}%`} onClick={()=>onSelect(g.house)}><span className="lm-gate-circle" style={{background:`conic-gradient(${progress===100?'#237c60':'#004aad'} ${progress}%,#e7e7e2 0)`}}><span>{g.house}</span></span><span className="lm-gate-name">{g.title}</span></button>})}</div>}
export default function GateOnboarding({scope,onHistory}:{scope:string;onHistory?:(drafts:StoryDraft[])=>void}){
 const key=`wishwell:gates:v1:${scope}`;const [state,setState]=useState<GateState>(()=>{try{return readGates(localStorage.getItem(key));}catch{return readGates(null);}});const [error,setError]=useState('');
 useEffect(()=>{onHistory?.(GATES.flatMap(g=>(state.records[g.house]?.history||[]).map((h,i)=>({id:`gate-${g.house}-${i}-${h.at}`,text:[h.wish,h.feeling?`How I feel: ${h.feeling}`:''].filter(Boolean).join('\n\n'),kind:'Wish',context:`Gate ${g.house} · ${g.title} · saved on this browser`}))));},[state]);
 const save=(next:GateState)=>{setState(next);try{localStorage.setItem(key,JSON.stringify(next));setError('');return true;}catch{setError('Progress is in memory only: this browser could not save it.');return false;}};
 const current=GATES.find(g=>g.house===state.selected)!;const day=GATES.indexOf(current);const record=state.records[current.house]||{wish:'',feeling:''};
 const update=(r:GateRecord)=>save({...state,records:{...state.records,[current.house]:r}});
 const select=(house:number)=>save({...state,selected:house,records:{...state.records,[house]:{wish:'',feeling:'',...state.records[house],opened:true}}});
 return <section className="lm-gate-onboarding" id="wish-well"><header className="lm-gate-intro"><p className="lm-kicker">BOARDING · YOUR UNIVERSAL FAMILY OFFICE</p><h1>Make your wishes work.</h1><p>Tell your story. We’ll find the work inside it—and grow toward your happily ever after.</p></header><div className="lm-gate-layout"><div><GateTree state={state} onSelect={select}/><p className="lm-caption lm-gate-legend">○ Unopened · blue: exploring · green: reviewed</p></div><div className="lm-gate-panel"><p className="lm-kicker">13 CONVERSATIONS · START ANYWHERE</p><div className="lm-gate-tabs" role="tablist" aria-label="Thirteen onboarding days">{GATES.map((g,i)=><button role="tab" key={g.house} id={`gate-tab-${g.house}`} aria-controls="gate-panel" aria-selected={g.house===state.selected} onClick={()=>select(g.house)}>{i+1}<span>{g.day}</span>{gateProgress(state.records[g.house])===100?' ✓':''}</button>)}</div><section role="tabpanel" id="gate-panel" aria-labelledby={`gate-tab-${current.house}`}><p className="lm-kicker">DAY {day+1} · GATE {current.house}</p><h2 className="lm-section-title">{current.day}</h2><p>{current.detail}</p><progress max={100} value={gateProgress(record)} aria-label={`${current.title} progress`}/><LorraineMadreChat key={`${scope}-${current.house}`} day={day} initialWords={record} context={`WISH WELL 13-gate journey. Gate ${current.house}: ${current.title}. ${current.context}. Start with this gentle question if needed: ${current.prompt}. The Hero tells stories; do not make them select record types. Identify candidate SMART Goals, Outcomes, tasks and documents; preserve unknowns. Reference existing work only when supplied. SOAP wishes internally: subjective words, objective evidence/unknowns, assessment of context/capacity, proposed plan. Make suggestions, not claims of executed records. Never require trauma disclosure.`} onWordsChange={w=>update({...record,...w,opened:true,reviewed:false})} onContribution={w=>{const history=[...(record.history||[])];const last=history[history.length-1];if(last?.wish!==w.wish||last?.feeling!==w.feeling)history.push({wish:w.wish,feeling:w.feeling,at:new Date().toISOString()});return update({...record,...w,opened:true,reviewed:false,history});}}/>
 {record.history?.length?<div className="lm-gate-review"><button className="lm-pill lm-pill-white" onClick={()=>update({...record,reviewed:!record.reviewed})}>{record.reviewed?'Reopen this gate':'This reflects my story ✓'}</button><details><summary>Your saved words · {record.history.length}</summary>{record.history.map((h,i)=><p key={i}>{h.wish}{h.feeling?` — ${h.feeling}`:''}</p>)}</details></div>:null}</section><p className="lm-caption" role={error?'alert':undefined}>{error||'Saved on this browser. A reviewed gate marks your reflection, not an activated service. Return in any order.'}</p></div></div></section>;
}
