import React,{useState,useEffect} from 'react';
import {GATES,GateState,GateRecord,readGates,gateProgress} from '../gates';
import LorraineMadreChat,{StoryDraft} from './LorraineMadreChat';
const ALT='WISH WELL map. Dream above Plan; Outcome and Document; the Engine at the center; Project and Wish; Goal; Backlog and Deal; Task; Routine; Base; Pride below.';
export function GateTree({state,onSelect}:{state:GateState;onSelect:(key:string)=>void}){
 return <div className="lm-gate-map"><img src="/wishwell/wishwell-map.webp" alt={ALT} width={640} height={642}/>{GATES.map(g=>{const progress=gateProgress(state.records[g.key]);return <button key={g.key} type="button" className={`lm-gate-spot is-${g.shape} ${state.selected===g.key?'is-current':''} ${progress===100?'is-reviewed':''}`} style={{left:`${g.x}%`,top:`${g.y}%`}} aria-pressed={state.selected===g.key} aria-label={`${g.title}: ${g.day}, ${progress}%`} title={`${g.title} · ${progress}%`} onClick={()=>onSelect(g.key)}>{progress>0&&<span className="lm-gate-badge" style={{background:`conic-gradient(#111 ${progress}%,#e7e7e2 0)`}}><span>{progress===100?'✓':''}</span></span>}</button>})}</div>;
}
export default function GateOnboarding({scope,onHistory}:{scope:string;onHistory?:(drafts:StoryDraft[])=>void}){
 const key=`wishwell:gates:v1:${scope}`;const [state,setState]=useState<GateState>(()=>{try{return readGates(localStorage.getItem(key));}catch{return readGates(null);}});const [error,setError]=useState('');
 useEffect(()=>{onHistory?.(GATES.flatMap(g=>(state.records[g.key]?.history||[]).map((h,i)=>({id:`gate-${g.key}-${i}-${h.at}`,text:[h.wish,h.feeling?`How I feel: ${h.feeling}`:''].filter(Boolean).join('\n\n'),kind:'Wish',context:`${g.title} · saved on this browser`}))));},[state]);
 const save=(next:GateState)=>{setState(next);try{localStorage.setItem(key,JSON.stringify(next));setError('');return true;}catch{setError('Progress is in memory only: this browser could not save it.');return false;}};
 const current=GATES.find(g=>g.key===state.selected)!;const day=GATES.indexOf(current);const record=state.records[current.key]||{wish:'',feeling:''};
 const update=(r:GateRecord)=>save({...state,records:{...state.records,[current.key]:r}});
 const select=(key:string)=>save({...state,selected:key,records:{...state.records,[key]:{wish:'',feeling:'',...state.records[key],opened:true}}});
 return <section className="lm-gate-onboarding" id="wish-well"><header className="lm-gate-intro"><p className="lm-kicker">BOARDING · YOUR UNIVERSAL FAMILY OFFICE</p><h1>Make your wishes work.</h1><p>Tell your story. We’ll find the work inside it—and grow toward your happily ever after.</p></header><div className="lm-gate-layout"><div><GateTree state={state} onSelect={select}/><p className="lm-caption lm-gate-legend">Tap any circle or word to begin. The small ring shows how far along each one is; ✓ means you reviewed it.</p></div><div className="lm-gate-panel"><p className="lm-kicker">14 CONVERSATIONS · START ANYWHERE</p><div className="lm-gate-tabs" role="tablist" aria-label="Fourteen onboarding conversations">{GATES.map((g,i)=><button role="tab" key={g.key} id={`gate-tab-${g.key}`} aria-controls="gate-panel" aria-selected={g.key===state.selected} onClick={()=>select(g.key)}><span className="lm-gate-dot" style={{background:g.shape==='word'?'transparent':g.color}} aria-hidden/>{i+1} · {g.title}{gateProgress(state.records[g.key])===100?' ✓':''}</button>)}</div><section role="tabpanel" id="gate-panel" aria-labelledby={`gate-tab-${current.key}`}><p className="lm-kicker">DAY {day+1} · {current.title.toUpperCase()}{current.house?` · HOUSE ${current.house}`:' · SOUTH NODE'}</p><h2 className="lm-section-title">{current.day}</h2><p>{current.detail}</p><progress className="lm-gate-progress" style={{['--gate' as string]:current.shape==='word'||current.key==='9'?'#111':current.color} as React.CSSProperties} max={100} value={gateProgress(record)} aria-label={`${current.title} progress`}/><LorraineMadreChat key={`${scope}-${current.key}`} day={day} initialWords={record} context={`WISH WELL map conversation: ${current.title}${current.house?` (House ${current.house})`:''}. ${current.context}. Start with this gentle question if needed: ${current.prompt}. The Hero tells stories; do not make them select record types. Identify candidate SMART Goals, Outcomes, tasks and documents; preserve unknowns. Reference existing work only when supplied. SOAP wishes internally: subjective words, objective evidence/unknowns, assessment of context/capacity, proposed plan. Make suggestions, not claims of executed records. Never require trauma disclosure.`} onWordsChange={w=>update({...record,...w,opened:true,reviewed:false})} onContribution={w=>{const history=[...(record.history||[])];const last=history[history.length-1];if(last?.wish!==w.wish||last?.feeling!==w.feeling)history.push({wish:w.wish,feeling:w.feeling,at:new Date().toISOString()});return update({...record,...w,opened:true,reviewed:false,history});}}/>
 {record.history?.length?<div className="lm-gate-review"><button className="lm-pill lm-pill-white" onClick={()=>update({...record,reviewed:!record.reviewed})}>{record.reviewed?'Reopen this gate':'This reflects my story ✓'}</button><details><summary>Your saved words · {record.history.length}</summary>{record.history.map((h,i)=><p key={i}>{h.wish}{h.feeling?` — ${h.feeling}`:''}</p>)}</details></div>:null}</section><p className="lm-caption" role={error?'alert':undefined}>{error||'Saved on this browser. A reviewed gate marks your reflection, not an activated service. Return in any order.'}</p></div></div></section>;
}
