import React,{useState} from 'react';
import {ENGINE_POSITIONS} from './EngineGrid';
const PARTS=['Holding company','Fund','Domains','Home server','Small product team','Nonprofit foundation','Church','Insurance','Trust','Career','CRM','Retirement'];
type Part={name:string;next:string;enabled:boolean};
export default function MothershipGrid({scope}:{scope:string}){
 const key=`wishwell:mothership:v1:${scope}`;
 const [parts,setParts]=useState<Record<string,Part>>(()=>{try{const x=JSON.parse(localStorage.getItem(key)||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x:{};}catch{return {};}});
 const [active,setActive]=useState<number|null>(null);const [error,setError]=useState('');
 const update=(i:number,p:Part)=>{const next={...parts,[i]:p};setParts(next);try{localStorage.setItem(key,JSON.stringify(next));setError('');}catch{setError('These edits could not be saved by this browser.');}};
 const count=PARTS.filter((_,i)=>parts[i]?.name?.trim()&&parts[i]?.next?.trim()).length;
 return <section className="lm-engine-shell"><h2 className="lm-section-title">Mothership</h2><p className="lm-caption">{count} / 12 components outlined · saved on this browser</p><progress value={count} max={12} aria-label="Mothership outline progress"/><div className="lm-engine-ring lm-line-grid">{PARTS.map((name,i)=>{const p=parts[i];return <button key={name} className="lm-engine-cell" style={{gridRow:ENGINE_POSITIONS[i][0],gridColumn:ENGINE_POSITIONS[i][1]}} onClick={()=>setActive(i)} aria-pressed={active===i}><small>{i+1} · {p?.enabled?'● In use':'○ Not in use'}</small><strong>{name}</strong><span>{p?.name||'Add details'}</span><progress value={Number(Boolean(p?.name?.trim()))+Number(Boolean(p?.next?.trim()))} max={2} aria-label={`${name} outline progress`}/></button>})}<div className="lm-engine-center"><p>Your mothership</p><small>{Math.round(count/12*100)}% outlined</small></div></div>{active!==null&&<div className="lm-day-focus"><h3>{PARTS[active]}</h3><label>Name<input value={parts[active]?.name||''} onChange={e=>update(active,{name:e.target.value,next:parts[active]?.next||'',enabled:parts[active]?.enabled||false})}/></label><label>What exists or needs doing next?<textarea value={parts[active]?.next||''} onChange={e=>update(active,{name:parts[active]?.name||'',next:e.target.value,enabled:parts[active]?.enabled||false})}/></label><label><input type="checkbox" checked={Boolean(parts[active]?.enabled)} onChange={e=>update(active,{name:parts[active]?.name||'',next:parts[active]?.next||'',enabled:e.target.checked})}/> I’m using this component</label><p className="lm-caption">Your status, not a verified connection.</p><button onClick={()=>setActive(null)}>Close</button></div>}{error&&<p role="alert">{error}</p>}</section>;
}
