import React,{useState} from 'react';
import {Entity} from '../types';
import {PLAN_SLOTS} from '../planSlots';
interface Props{entities:Entity[];onSelect:(id:string)=>void;onUpdate:(e:Entity)=>void}
export default function SpaceBoard({entities,onSelect,onUpdate}:Props){
 const [editing,setEditing]=useState<string|null>(null);const entity=entities.find(e=>e.id===editing);const queen=entities.find(e=>e.type==='church');
 return <section aria-label="Space board"><div className="lm-board-heading"><div><h2 className="lm-section-title">Space · the Plan board</h2><p>16 standing Plans. One Goal, eight Outcomes and 64 Task spaces inside each.</p></div>{queen&&<button className="lm-queen" onClick={()=>setEditing(queen.id)} aria-label="Queen — view or assign person" title={queen.assignment?.name||'Queen · no person assigned'}>♛<span>Queen</span></button>}</div><div className="lm-plan-board">{PLAN_SLOTS.map((slot,i)=>{const e=entities.find(e=>e.id===slot.entityId);const a=e?.assignment;return <article key={slot.slot} className={`lm-plan-tile ${(Math.floor(i/4)+i%4)%2?'is-dark':''}`}><small>{slot.glyph} {slot.planet}</small><button className="lm-plan-open" disabled={!e} onClick={()=>e&&onSelect(e.id)}>{e?.name||'Name this Plan'}</button><span>{slot.system}</span><button className="lm-chess" disabled={!e} onClick={()=>e&&setEditing(e.id)} aria-label={`${slot.planet}: ${a?.name||'assign a person'}`}><span aria-hidden="true">{a?.piece||'♙'}</span><span className="lm-person-popover"><strong>{a?.name||'No person assigned'}</strong><br/>{a?.role||'Add someone to this space'}<br/>Goals: {a?.goals.join('; ')||'None assigned'}<br/>Tasks: {a?.tasks.join('; ')||'None assigned'}</span></button></article>})}</div>{entity&&<Assignment key={entity.id} entity={entity} onClose={()=>setEditing(null)} onSave={e=>{onUpdate(e);setEditing(null)}}/>}</section>
}
function Assignment({entity,onClose,onSave}:{entity:Entity;onClose:()=>void;onSave:(e:Entity)=>void}){const [name,setName]=useState(entity.assignment?.name||'');const [role,setRole]=useState(entity.assignment?.role||'');const [goals,setGoals]=useState(entity.assignment?.goals.join('\n')||'');const [tasks,setTasks]=useState(entity.assignment?.tasks.join('\n')||'');const [piece,setPiece]=useState(entity.assignment?.piece||'♙');return <section className="lm-assignment" aria-label="Person and assignments"><button className="lm-pill" onClick={onClose}>Close</button><h3>Who belongs in this space?</h3><p>{entity.name} · person details and assignments for this session</p><form onSubmit={e=>{e.preventDefault();const lines=(s:string)=>s.split('\n').map(x=>x.trim()).filter(Boolean);onSave({...entity,assignment:{name:name.trim(),role:role.trim(),goals:lines(goals),tasks:lines(tasks),piece}})}}><label>Person’s name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)}/></label>{entity.type!=='church'&&<label>Chess piece<select value={piece} onChange={e=>setPiece(e.target.value)}>{['♙','♖','♘','♗','♔'].map(x=><option key={x}>{x}</option>)}</select></label>}<label>Assigned Goals · one per line<textarea value={goals} onChange={e=>setGoals(e.target.value)}/></label><label>Assigned Tasks · one per line<textarea value={tasks} onChange={e=>setTasks(e.target.value)}/></label><button className="lm-pill">Keep assignment</button></form></section>}
