// WISH WELL interpretation, not a claim about a historical Tree of Life diagram.
export const GATES = [
 {house:6,title:'Intention & Pride',day:'Your people',prompt:'Who is beside you, what comes naturally to you, and what would you like more room for?',detail:'Relationships, talents and the support you want. Share only what feels useful.',context:'Pride is the small product team. Juno: relationships; Vesta: talents; Chiron: healing/trauma. Invite strengths and support needs; never require trauma disclosure.',x:280,y:805},
 {house:4,title:'Base',day:'Your home base',prompt:'Where does your life happen—and where do your files, tools and unfinished ideas live?',detail:'Begin with your existing home and digital base.',context:'Google can be the initial digital base, with a pathway to a personal home server. Do not assume either is connected.',x:280,y:580},
 {house:5,title:'Tasks',day:'Your real day',prompt:'Walk me through a real day. What keeps asking for your attention?',detail:'Small actions, responsibilities and things you want off your mind.',context:'Tasks belong to House 5. Distinguish an action from a project or outcome without correcting the Hero.',x:130,y:610},
 {house:13,title:'Routine · Earth',day:'Your rhythm',prompt:'When do you have room to care, create, rest or ask for help?',detail:'Bring your people, base and daily work into a rhythm.',context:'House 13 is Routine/Earth combining gates 5, 4 and 6. Four six-hour blocks: night, morning, afternoon, evening. Existing routine before prescribed priorities.',x:280,y:700},
 {house:11,title:'Wishes',day:'What you hear',prompt:'What do you keep wishing for—and what do your people keep asking for?',detail:'Your wishes and the wishes of the people you serve.',context:'House 11 is wish data: personal, team and customer stories. A wish can lead to a goal, deal, document or tasks.',x:130,y:370},
 {house:3,title:'Goals',day:'What could change',prompt:'If one of those stories changed for the better, what would be different?',detail:'Describe the change. Lorraen helps make it clear and measurable.',context:'Goals are central and may arise from wishes, projects, plans, backlogs, tasks or deals. Propose SMART wording; ask for unknown measures, dates and scope instead of inventing them.',x:280,y:350},
 {house:1,title:'Projects',day:'What you’re building',prompt:'What are you bringing into the world, or keeping alive, over the next six months?',detail:'Give an existing venture or idea a place to grow.',context:'Planets are Projects on a six-month cadence with Lean Value Canvases. Each Project has a Goal. Only attach a Plan if outcomes exist.',x:130,y:250},
 {house:2,title:'Deals',day:'Give & receive',prompt:'What could you offer, what do you need, and who might you work with?',detail:'Offers, exchanges and agreements worth exploring.',context:'Deals belong to House 2 and have a Goal. They are not completed agreements without evidence.',x:430,y:250},
 {house:8,title:'Outcomes',day:'What progress looks like',prompt:'What could you point to and say: that is working?',detail:'Evidence of change, in your own words.',context:'Outcomes are evidence of the Goal being realized. North Node relates to outcomes and retirement direction. Do not equate completed tasks with outcomes.',x:130,y:490},
 {house:9,title:'Plan',day:'Bring it together',prompt:'Which change matters enough to make room for—and what would help you get there?',detail:'One Goal, eight Outcome spaces and 64 Task spaces.',context:'A Plan has one Goal, eight Outcomes and 64 task spaces. Keep unknown spaces empty. North Node: outcomes/retirement; South Node: documents, nonprofit foundation, mission and where the work goes. Reuse existing Plans before proposing another.',x:280,y:150},
 {house:10,title:'Backlog',day:'Keep the loose threads',prompt:'What still needs doing, even if now is not the time?',detail:'Keep tasks together without making everything urgent.',context:'House 10 is the backlog: tasks gathered across the work. Preserve existing tasks and links; do not autoassign priorities.',x:430,y:370},
 {house:7,title:'Engine',day:'How it keeps working',prompt:'What would help this keep moving when life gets busy?',detail:'Support, coordination and a rhythm you can return to.',context:'House 7 coordinates the daily Engine. Lines of care: telemedicine, insurance, legal, travel, technology, financial. Connections require verification.',x:430,y:490},
 {house:12,title:'Dream',day:'Your happily ever after',prompt:'With all of this in place, what does the life you are growing toward feel like?',detail:'Your Dream holds the whole picture and the manifestations of every House.',context:'House 12 is the Dream, outside/above the ten-gate inner map in this WISH WELL interpretation. It contains goals, plans, tasks, outcomes, prides and bases. Do not present this product map as historical doctrine.',x:280,y:45},
];
export type GateRecord={opened?:boolean;wish:string;feeling:string;reviewed?:boolean;history?:{wish:string;feeling:string;at:string}[]};
export type GateState={version:1;selected:number;records:Record<string,GateRecord>};
export const freshGates=():GateState=>({version:1,selected:6,records:{}});
export function readGates(raw:string|null):GateState{try{const p=JSON.parse(raw||'null');const s=freshGates();if(p?.version!==1)return s;if(GATES.some(g=>g.house===p.selected))s.selected=p.selected;for(const g of GATES){const r=p.records?.[g.house];if(r&&typeof r.wish==='string'&&typeof r.feeling==='string')s.records[g.house]={...r,opened:r.opened===true,reviewed:r.reviewed===true,history:Array.isArray(r.history)?r.history.filter((v:any)=>v&&typeof v.wish==='string'&&typeof v.feeling==='string'&&typeof v.at==='string'):[]};}return s;}catch{return freshGates();}}
export const gateProgress=(r?:GateRecord)=>r?.reviewed&&r.history?.length?100:r?.history?.length?60:r?.opened?15:0;
